server:
  port: 18081
# For actuator endpoints exposure
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  application:
    name: service-provider1
  cloud:
    nacos:
      server-addr: 135.252.247.212:8848
      discovery:
        weight: 1.0
        metadata:
          version: v1
          command-group: ${cnnbi.topa.service.command-group}
          command-code: ${cnnbi.topa.service.command-code}

  config:
    import:
      - optional:nacos:service-provider1.yml
      - optional:nacos:service.xml

user:
  name: Zhang San
  age: 18

cnnbi.topa.service:
  command-group: cnnbi-sa
  command-code: ADD-ONU,DEL-ONU,ADD-PONVLAN,DEL-PONVLAN