server:
  port: 18080
# For actuator endpoints exposure
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  application:
    name: nacos-example
  cloud:
    nacos:
      server-addr: 135.252.247.212:8848
      discovery:
        weight: 1.0
        metadata:
          version: v1
          command-codes: ADD-ONU,ADD-PONVLAN,DEL-ONU,DEL-PONVLAN

  config:
    import:
      - optional:nacos:nacos-example.yml
      - optional:nacos:service.xml
