server:
  port: 18082
# For actuator endpoints exposure
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  application:
    name: service-provider2
  cloud:
    nacos:
      server-addr: 135.252.247.212:8848
      discovery:
        weight: 1.0
        metadata:
          version: v1
          command-group: ${cnnbi.topa.service.command-group}
          command-code: ${cnnbi.topa.service.command-code}

  config:
    import:
      - optional:nacos:service-provider2.yaml
      - optional:nacos:service.xml

user:
  name: Zhang San
  age: 18

cnnbi.topa.service:
  command-group: cnnbi-in
  command-code: LST-DEVICE,LST-ONU,LST-PORTVLAN