server:
  port: 18080
# For actuator endpoints exposure
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  application:
    name: service-consumer
  cloud:
    nacos:
      server-addr: 135.252.247.212:8848

  config:
    import:
      - optional:nacos:service-consumer.yml
      - optional:nacos:user.properties
      - optional:nacos:service.xml
  freemarker:
    template-loader-path:
      - file:\C:\Code\nacos-samples\service-consumer\src\main\resources\templates
#      - classpath:/templates/


user:
  name: Zhang San
  age: 18

cnnbi.topa.application:
  command-group:
    enabled: false
    groups:
      cnnbi-sa:
        - ADD-ONU
        - DEL-ONU
      cnnbi-in:
        - LST-ONU
        - LST-DEVICE